name: "Lint: Helm"

on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint:
    name: helm lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
      - run: helm lint chart/hcloud-image-controller

  template:
    name: helm template
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
      - run: helm template test chart/hcloud-image-controller --namespace hcloud-image-system
